import Navbar from "./Navbar"
import Footer from "./Footer"
import Head from "next/head"

export default function Layout({children}){

    return (
        <>
        <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imagens/favicon.ico" />
        </Head>
        <Navbar/>
        <main className="mainContainer">
            {children}
        </main>
        <Footer/>
        </>
    )
}